name: ISC
favicon: null
layout_spectrum: 0.3220359680708498
typography_spectrum: 0.29622256103903055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9148585551884025
  lightness: 0.9344017414841801
  saturation: 0.2530238979961723
  rhythmicContrast: 0.23003789712674916
purpose: []
